/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    container: { center: true, padding: '2rem', screens: { '2xl': '1400px' } },
    extend: {
      colors: {
        border:     'hsl(var(--border))',
        input:      'hsl(var(--input))',
        ring:       'hsl(var(--ring))',
        background: '#0a0a0b',
        foreground: '#ebe6da',
        card:       '#0a0a0b',
        'card-foreground': '#ebe6da',
        popover:    '#0a0a0b',
        'popover-foreground': '#ebe6da',
        muted:      '#141316',
        'muted-foreground': '#958da1',
        accent:     '#2b2a2e',
        'accent-foreground': '#ebe6da',
        destructive: '#e5484d',
        'destructive-foreground': '#ffffff',

        // GDS Frame brand kit — template preto e dourado. Dourado (primary) é o
        // accent dominante de ação/marca; Royal Blue (tertiary) fica reservado a
        // foco, links e estados interativos secundários.
        "on-secondary-fixed-variant": "#12224f",
        "primary-container": "#3d3011",
        "surface": "#0a0a0b",
        "surface-variant": "#2b2a2e",
        "on-secondary-container": "#dbe2fd",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#050505",
        "on-secondary": "#ffffff",
        "surface-container-high": "#1c1b1f",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#0a1230",
        "surface-tint": "#c9a24b",
        "on-primary-fixed-variant": "#3d3011",
        "on-primary-fixed": "#2b2110",
        "on-primary-container": "#f5e5c2",
        "secondary-fixed": "#9db0fa",
        "tertiary-container": "#12224f",
        "inverse-on-surface": "#26252a",
        "surface-container": "#141316",
        "secondary-container": "#1e2f6e",
        "on-primary": "#0a0a0b",
        "inverse-surface": "#ebe6da",
        "surface-container-low": "#100f12",
        "on-tertiary-fixed-variant": "#12224f",
        "surface-bright": "#28272c",
        "tertiary-fixed-dim": "#6f8bf7",
        "primary": { DEFAULT: "#c9a24b", foreground: "#0a0a0b" },
        "tertiary": "#2e4fe3",
        "outline": "#958da1",
        "primary-fixed": "#f0dfae",
        "surface-container-highest": "#2b2a2e",
        "outline-variant": "#4a4455",
        "primary-fixed-dim": "#d9b76c",
        "on-error": "#690005",
        "inverse-primary": "#8a6d2f",
        "on-surface-variant": "#ccc3d8",
        "secondary-fixed-dim": "#2e4fe3",
        "on-tertiary-container": "#dbe2fd",
        "on-background": "#ebe6da",
        "on-surface": "#ebe6da",
        "on-secondary-fixed": "#0a1230",
        "secondary": { DEFAULT: "#2e4fe3", foreground: "#ffffff" },
        "surface-dim": "#0a0a0b",
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",

        // Keep existing legacy
        jebai:      'hsl(var(--jebai))',
        paje1:      'hsl(var(--paje1))',
        paje2:      'hsl(var(--paje2))',
        meta1:      'hsl(var(--meta1))',
        meta2:      'hsl(var(--meta2))',
        meta3:      'hsl(var(--meta3))',
        mkt:        'hsl(var(--mkt))',
        caixa:      'hsl(var(--caixa))',
      },
      borderRadius: {
        lg: '0.5rem',
        md: 'calc(0.5rem - 2px)',
        sm: 'calc(0.5rem - 4px)',
        xl: '0.75rem',
      },
      spacing: {
        "margin-page": "32px",
        "stack-lg": "24px",
        "card-padding": "20px",
        "base": "4px",
        "gutter": "24px",
        "stack-md": "16px",
        "stack-sm": "8px"
      },
      fontFamily: {
        "headline-lg-mobile": ["var(--font-hanken)"],
        "label-sm": ["var(--font-jetbrains)"],
        "body-base": ["var(--font-manrope)"],
        "headline-lg": ["var(--font-hanken)"],
        "title-md": ["var(--font-manrope)"],
        "display-lg": ["var(--font-hanken)"],
        sans: ["var(--font-manrope)", 'sans-serif'],
        mono: ["var(--font-jetbrains)", 'monospace'],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "body-base": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
        "title-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up':   { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up':   'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
