/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    container: { center: true, padding: '2rem', screens: { '2xl': '1400px' } },
    extend: {
      colors: {
        border:     'hsl(var(--border))',
        input:      'hsl(var(--input))',
        ring:       'hsl(var(--ring))',
        background: '#0b1326',
        foreground: '#dae2fd',
        card:       '#0b1326',
        'card-foreground': '#dae2fd',
        popover:    '#0b1326',
        'popover-foreground': '#dae2fd',
        muted:      '#171f33',
        'muted-foreground': '#958da1',
        accent:     '#2d3449',
        'accent-foreground': '#dae2fd',
        destructive: '#e5484d',
        'destructive-foreground': '#ffffff',

        // GDS palette — single accent: Royal Blue. Gold (secondary) reserved for achievement.
        "on-secondary-fixed-variant": "#574500",
        "primary-container": "#1e3a8a",
        "surface": "#0b1326",
        "surface-variant": "#2d3449",
        "on-secondary-container": "#342800",
        "on-tertiary": "#06283d",
        "surface-container-lowest": "#060e20",
        "on-secondary": "#3c2f00",
        "surface-container-high": "#222a3d",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#06283d",
        "surface-tint": "#3b82f6",
        "on-primary-fixed-variant": "#1e3a8a",
        "on-primary-fixed": "#0a1f4d",
        "on-primary-container": "#dbeafe",
        "secondary-fixed": "#ffe088",
        "tertiary-container": "#1e3a5f",
        "inverse-on-surface": "#283044",
        "surface-container": "#171f33",
        "secondary-container": "#af8d11",
        "on-primary": "#ffffff",
        "inverse-surface": "#dae2fd",
        "surface-container-low": "#131b2e",
        "on-tertiary-fixed-variant": "#1e3a5f",
        "surface-bright": "#31394d",
        "tertiary-fixed-dim": "#60a5fa",
        "primary": { DEFAULT: "#3b82f6", foreground: "#ffffff" },
        "tertiary": "#5b9bd5",
        "outline": "#958da1",
        "primary-fixed": "#bfdbfe",
        "surface-container-highest": "#2d3449",
        "outline-variant": "#4a4455",
        "primary-fixed-dim": "#60a5fa",
        "on-error": "#690005",
        "inverse-primary": "#1d4ed8",
        "on-surface-variant": "#ccc3d8",
        "secondary-fixed-dim": "#e9c349",
        "on-tertiary-container": "#cfe0f5",
        "on-background": "#dae2fd",
        "on-surface": "#dae2fd",
        "on-secondary-fixed": "#241a00",
        "secondary": { DEFAULT: "#e9c349", foreground: "#3c2f00" },
        "surface-dim": "#0b1326",
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",

        // Keep existing legacy
        jebai:      'hsl(var(--jebai))',
        paje1:      'hsl(var(--paje1))',
        paje2:      'hsl(var(--paje2))',
        meta1:      'hsl(var(--meta1))',
        meta2:      'hsl(var(--meta2))',
        meta3:      'hsl(var(--meta3))',
        mkt:        'hsl(var(--mkt))',
        caixa:      'hsl(var(--caixa))',
      },
      borderRadius: {
        lg: '0.5rem',
        md: 'calc(0.5rem - 2px)',
        sm: 'calc(0.5rem - 4px)',
        xl: '0.75rem',
      },
      spacing: {
        "margin-page": "32px",
        "stack-lg": "24px",
        "card-padding": "20px",
        "base": "4px",
        "gutter": "24px",
        "stack-md": "16px",
        "stack-sm": "8px"
      },
      fontFamily: {
        "headline-lg-mobile": ["var(--font-hanken)"],
        "label-sm": ["var(--font-jetbrains)"],
        "body-base": ["var(--font-manrope)"],
        "headline-lg": ["var(--font-hanken)"],
        "title-md": ["var(--font-manrope)"],
        "display-lg": ["var(--font-hanken)"],
        sans: ["var(--font-manrope)", 'sans-serif'],
        mono: ["var(--font-jetbrains)", 'monospace'],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "body-base": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
        "title-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up':   { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up':   'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
